import React from 'react';

export const categoriesData = [
  {
    name: 'Marketing & Sale',
    image: '/marketing.svg',
    jobs: [
      {
        title: 'Digital Marketing Specialist',
        company: 'LinkedIn',
        companyImage: 'https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/e9/13/57/e91357b4-c087-bfa3-1e69-5aebff3772f6/AppIcon-0-1x_U007emarketing-0-8-0-85-220-0.png/1200x600wa.png',
        location: 'New York, US',
        type: 'Fulltime',
        posted: '4 minutes ago',
        description: 'Manage digital campaigns and increase brand awareness.',
        salary: '$500/Hour',
      },
      {
        title: 'Sales Manager',
        company: 'Google',
        companyImage: 'https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/9d/6c/3b/9d6c3b1f-376d-03c3-2672-a9d92018acfa/logo_gsa_gradient_ios_color-0-1x_U007epad-0-0-0-1-0-0-sRGB-0-0-85-220-0.png/1200x630wa.png',
        location: 'Mountain View, US',
        type: 'Fulltime',
        posted: '2 hours ago',
        description: 'Lead sales strategies and grow customer base.',
        salary: '$600/Hour',
      },
      {
        title: 'Content Strategist',
        company: 'Facebook',
        companyImage: 'https://www.wavetransit.com/wp-content/uploads/2021/08/Facebook-logo.png',
        location: 'Menlo Park, US',
        type: 'Part-time',
        posted: '1 day ago',
        description: 'Create content plans to engage users.',
        salary: '$400/Hour',
      },
      {
        title: 'SEO Analyst',
        company: 'Amazon',
        companyImage: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/ad/f5/24/adf524b5-f8d1-31b3-eaf5-2a9f9afe96ef/AppIcon-0-0-1x_U007epad-0-1-0-0-85-220.png/1200x630wa.png',
        location: 'Seattle, US',
        type: 'Contract',
        posted: '3 days ago',
        description: 'Optimize web content to rank higher in search.',
        salary: '$350/Hour',
      },
      {
        title: 'Brand Manager',
        company: 'Apple',
        companyImage: 'https://1000logos.net/wp-content/uploads/2017/02/Apple-Logosu.png',
        location: 'Cupertino, US',
        type: 'Fulltime',
        posted: '5 hours ago',
        description: 'Manage and grow brand identity.',
        salary: '$550/Hour',
      },
    ],
  },
  {
    name: 'Customer Help',
    image: '/customer.svg',
    jobs: [
      {
        title: 'Customer Support Agent',
        company: 'Zendesk',
        companyImage: 'https://etimg.etb2bimg.com/thumb/msid-114333157,imgsize-6570,width-1200,height=765,overlay-etciosea/news/corporate/zendesk-builds-on-complete-service-solution-to-strengthen-human-and-ai-partnership.jpg',
        location: 'Remote',
        type: 'Fulltime',
        posted: '10 minutes ago',
        description:
          'Assist customers with inquiries and problems via phone and chat.',
        salary: '$25/Hour',
      },
      {
        title: 'Technical Support Specialist',
        company: 'Cisco',
        companyImage: 'https://www.packetcoders.io/content/images/2024/07/Cisco.webp',
        location: 'San Jose, US',
        type: 'Fulltime',
        posted: '1 hour ago',
        description: 'Resolve technical issues for clients.',
        salary: '$35/Hour',
      },
      {
        title: 'Help Desk Analyst',
        company: 'Dell',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOcRLW8_cFaA_3dQ1KADHRRYQFtYlwl9B-eQ&s',
        location: 'Austin, US',
        type: 'Contract',
        posted: '2 days ago',
        description: 'Provide IT support and troubleshooting.',
        salary: '$30/Hour',
      },
      {
        title: 'Customer Experience Manager',
        company: 'Salesforce',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgx3H8Yf0HRcVH9SpaKSE5rXROs8B9eOJSTw&s',
        location: 'San Francisco, US',
        type: 'Fulltime',
        posted: '5 hours ago',
        description: 'Improve customer satisfaction and loyalty.',
        salary: '$45/Hour',
      },
      {
        title: 'Call Center Representative',
        company: 'Verizon',
        companyImage: 'https://cdn.mos.cms.futurecdn.net/7aXJTdPi2u7zsPSGgkDhbe.png',
        location: 'New Jersey, US',
        type: 'Fulltime',
        posted: '30 minutes ago',
        description: 'Handle inbound and outbound calls professionally.',
        salary: '$22/Hour',
      },
    ],
  },
  {
    name: 'Finance',
    image: '/finance (2).svg',
    jobs: [
      {
        title: 'Financial Analyst',
        company: 'JPMorgan',
        companyImage: 'https://pbs.twimg.com/profile_images/1605200105799401474/9cb5qdVk_400x400.png',
        location: 'New York, US',
        type: 'Fulltime',
        posted: '4 hours ago',
        description:
          'Analyze financial data and create reports for management.',
        salary: '$70/Hour',
      },
      {
        title: 'Accountant',
        company: 'Ernst & Young',
        companyImage: 'https://i0.wp.com/opportunitycell.com/wp-content/uploads/2020/12/EY-logo-Careers-Portal.jpg.png?resize=950%2C500&ssl=1',
        location: 'Chicago, US',
        type: 'Fulltime',
        posted: '1 day ago',
        description: 'Manage accounts and financial statements.',
        salary: '$60/Hour',
      },
      {
        title: 'Investment Banker',
        company: 'Goldman Sachs',
        companyImage: 'https://pbs.twimg.com/profile_images/1441140440791617537/JICPNdbf_400x400.png',
        location: 'New York, US',
        type: 'Fulltime',
        posted: '3 days ago',
        description: 'Advise clients on financial transactions.',
        salary: '$120/Hour',
      },
      {
        title: 'Auditor',
        company: 'KPMG',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCLvx1x8oeXs-DidUVmNti1LMUwkdDG3Fn0Q&s',
        location: 'Los Angeles, US',
        type: 'Contract',
        posted: '5 hours ago',
        description: 'Conduct audits and review financial documents.',
        salary: '$55/Hour',
      },
      {
        title: 'Credit Analyst',
        company: 'Wells Fargo',
        companyImage: 'https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/36/3b/be/363bbecd-f760-2801-728c-895056b19473/AppIcon-0-0-1x_U007epad-0-0-0-11-0-0-sRGB-85-220.png/1200x600wa.png',
        location: 'San Francisco, US',
        type: 'Fulltime',
        posted: '1 hour ago',
        description: 'Evaluate creditworthiness of loan applicants.',
        salary: '$65/Hour',
      },
    ],
  },
  {
    name: 'Software Development',
    image: '/lightning.svg',
    jobs: [
      {
        title: 'Frontend Developer',
        company: 'Netflix',
        companyImage: 'https://cdn-images-1.medium.com/max/1200/1*ty4NvNrGg4ReETxqU2N3Og.png',
        location: 'Los Gatos, US',
        type: 'Fulltime',
        posted: '10 minutes ago',
        description: 'Build user-friendly web interfaces.',
        salary: '$80/Hour',
      },
      {
        title: 'Backend Developer',
        company: 'Spotify',
        companyImage: 'https://m.media-amazon.com/images/I/31B2Nyzd8XL.png',
        location: 'Stockholm, Sweden',
        type: 'Fulltime',
        posted: '3 hours ago',
        description: 'Develop and maintain server-side logic.',
        salary: '$90/Hour',
      },
      {
        title: 'Full Stack Developer',
        company: 'Uber',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKT_FfKdClSYInd3yXKCbqZ06gDOwg0FTMUg&s',
        location: 'San Francisco, US',
        type: 'Fulltime',
        posted: '1 day ago',
        description: 'Work on both frontend and backend systems.',
        salary: '$95/Hour',
      },
      {
        title: 'Mobile App Developer',
        company: 'Airbnb',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQevTnEB6cgDu3l67PT0xzr3DDb9IAlz5TsSw&s',
        location: 'San Francisco, US',
        type: 'Contract',
        posted: '5 days ago',
        description: 'Build mobile applications for iOS and Android.',
        salary: '$85/Hour',
      },
      {
        title: 'DevOps Engineer',
        company: 'Docker',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnnfgtpti87GEM1h3RUYkSBOBPvtxCCiI8Yw&s',
        location: 'San Francisco, US',
        type: 'Fulltime',
        posted: '2 hours ago',
        description: 'Manage infrastructure and deployment pipelines.',
        salary: '$100/Hour',
      },
    ],
  },
  {
    name: 'Design',
    image: '/human.svg',
    jobs: [
      {
        title: 'UI/UX Designer',
        company: 'Adobe',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIXzLDp6hc9HBXPmY7PVd_7YlRZmULz8rdgg&s',
        location: 'San Jose, US',
        type: 'Fulltime',
        posted: '15 minutes ago',
        description: 'Design user-friendly software interfaces.',
        salary: '$70/Hour',
      },
      {
        title: 'Graphic Designer',
        company: 'Canva',
        companyImage: 'https://yt3.googleusercontent.com/M7S2_gnnaJT5buAfWW4tanX9NELz5PddzNCQgnRV1oP8t12s5pg4cYKMChkEoh8gtGX__KtcYKU=s900-c-k-c0x00ffffff-no-rj',
        location: 'Sydney, Australia',
        type: 'Part-time',
        posted: '1 day ago',
        description: 'Create graphics and visual content.',
        salary: '$45/Hour',
      },
      {
        title: 'Product Designer',
        company: 'Dropbox',
        companyImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4s3ECJJwiCX0hLvu4r9XHOEXMjqhxJ6T-PQ&s',
        location: 'San Francisco, US',
        type: 'Fulltime',
        posted: '3 days ago',
        description: 'Design and prototype product features.',
        salary: '$75/Hour',
      },
      {
        title: 'Motion Designer',
        company: 'Pixar',
        companyImage: 'https://media.licdn.com/dms/image/v2/D560BAQGweVEucihVrw/company-logo_200_200/company-logo_200_200/0/1725600535833/pixar_animation_studios_logo?e=2147483647&v=beta&t=2-09-j37dEanuEEzAYkbA5EVAPv3MEZGfAg-s7zA34A',
        location: 'Emeryville, US',
        type: 'Contract',
        posted: '1 week ago',
        description: 'Create motion graphics and animations.',
        salary: '$80/Hour',
      },
      {
        title: 'Illustrator',
        company: 'National Geographic',
        companyImage: 'https://yt3.googleusercontent.com/ytc/AIdro_kKGaEKaafkVObI-xJQPOipJ-B-W2vdD8fuv4oNEW7d894=s900-c-k-c0x00ffffff-no-rj',
        location: 'Washington DC, US',
        type: 'Fulltime',
        posted: '2 days ago',
        description: 'Produce illustrations for publications.',
        salary: '$60/Hour',
      },
    ],
  },
];
